[build]
  command = "./build-netlify.sh"
  publish = "wordris-svelte/build"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_CONFIG_PRODUCTION = "false"
  YARN_ENABLED = "false"
  USE_NPM = "true"
  NPM_VERSION = "10"
  NETLIFY_USE_YARN = "false"
  FORCE_NPM = "true"

[functions]
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173

[[headers]]
  for = "/build/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age-31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"